#!/usr/bin/env bash

git clone --bare git@github.com:Stackblocks/dotfiles.git $HOME/.dotfiles

# define dotconfig alias locally since the dotfiles
# aren't installed on the system yet
function dotconfig {
   git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

# create a directory to backup existing dotfiles to
mkdir -p .dotfiles-backup
dotconfig checkout
if [ $? = 0 ]; then
  echo "Checked out dotfiles from git@github.com:Stackblocks/dotfiles.git";
  else
    echo "Moving existing dotfiles to ~/.dotfiles-backup";
    dotconfig checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi

# checkout dotfiles from repo
dotconfig checkout
dotconfig config status.showUntrackedFiles no